title: Code Monkeys Lessons 
description: "August 2023 to June 2024"
owner_name: Code Monkeys
github_username: Tirth-Thakkar
github_repo: "Monkeys38"
baseurl: "/Monkeys38"
remote_theme: jekyll/minima
minima:
 # social_links:
 #   - { platform: github, user_url: "https://github.com/Tirth-Thakkar"}

# remote_theme: pages-themes/dinky@v0.2.0
# remote_theme: pages-themes/minimal@v0.2.0
# remote_theme: pages-themes/hacker@v0.2.0
# remote_theme: pages-themes/cayman@v0.2.0
# remote_theme: pages-themes/time-machine@v0.2.0
plugins:
- jekyll-remote-theme
future: true
